function safe_ncwriteatt( ...
    ncfile, location, attname, attvalue)

maxAttempts = 8;

for attempt = 1:maxAttempts

    try
        ncwriteatt( ...
            ncfile, ...
            location, ...
            attname, ...
            attvalue);
        return

    catch ME

        fprintf(['[NETCDF] Falló atributo "%s". ', ...
                 'Intento %d de %d.\n'], ...
                attname, attempt, maxAttempts);

        if attempt == maxAttempts

            newME = MException(['No fue posible escribir el atributo "%s" después ', ...
                 'de %d intentos en:\n%s\n\nCausa original:\n%s'], ...
                attname, ...
                maxAttempts, ...
                ncfile, ...
                getReport(ME, ...
                    'extended', ...
                    'hyperlinks', 'off'));

            newME = addCause(newME, ME);
            throwAsCaller(newME)
        end

        pause(0.20 * attempt);
    end
end

end