function write_qc_variable(ncfile, varname, data, dims, datatype, units, long_name)

extra_args = {};

if strcmp(datatype, 'uint8')
    extra_args = {
        'flag_values', uint8([0 1]), ...
        'flag_meanings', 'failed passed'
        };
end

wsa_nc_create_var( ...
    ncfile, ...
    varname, ...
    dims, ...
    datatype, ...
    'units', units, ...
    'long_name', long_name, ...
    extra_args{:});

safe_ncwrite( ...
    ncfile, ...
    varname, ...
    data);

end