function write_att_or_var(ncfile, var, attname, varname, dims, datatype, long_name)
    if all(var == var(1))
        ncwriteatt(ncfile, '/', ...
            attname, var(1));
    else
        wsa_nc_create_var(ncfile, ...
            varname, ...
            dims, ...
            datatype, ...
            'long_name', long_name);
    
        safe_ncwrite(ncfile, varname, var);
    end
end